### ISSUE TITLE
Disassembly displays ZP addressing in brackets even though it's not indirect.

### ISSUE THREAD

**Issue by kieranhj** [shawty/BBCB_DFS_Catalog#4]
E.g. the first 3 instructions of CORE in Stunt Car Racer: http://bbcmicro.co.uk/explore.php?id=3112 appear as:

```
0e00   86 16       STX (&16)
0e02   a5 52       LDA (&52)
0e04   85 14       STA (&14)

```
But actually should just be:

```
0e00   86 16       STX  &16
0e02   a5 52       LDA &52
0e04   85 14       STA &14
```

**Comment by shawty** [comment]
Thanks @kieranhj 

I'll add them to my list.

It may be slow progress getting around to them, but as long as I know they are there, I'll make sure I address them in the re-write of this.

Originally I only did the DFS reading part, this was another developer that added the basic/asm/screen display etc stuff in.

**Comment by pau1ie** [comment]
The other developer was me. I notice yet another developer has fixed this bug. I might try to get a PR together to incorporate the fix.

**Comment by shawty** [comment]
Great stuff @pau1ie - merged.
