### ISSUE TITLE
Incorrect disassembly of 0xB1 LDA (zp),Y

### ISSUE THREAD

**Issue by fivemack** [shawty/BBCB_DFS_Catalog#8]
EG at offset 0x4519 in http://bbcmicro.co.uk/explore.php?id=30

we have 

4519   b1 72 91    LDA (&9172,Y)

where the disassembly should have been

4519 b1 72 LDA (&72),Y

So it's a two-byte not a three-byte instruction and the rest of the disassembly goes off alignment.

I think you have the same issue with &91 STA (zp),Y and indeed with all instructions with bottom 5 bits b10001.

The Web disassembly view is really handy but this issue makes it much less usable.

**Comment by shawty** [comment]
Hi @fivemack ,

I have a re-write of all of this in progress (I really need to get my backside in gear)

The disassembly stuff was actually added after I wrote the original disk lister, but work and everything else keeps getting in the way.

Thanks for noting this here, it keeps it where I can find it when I do get to doing some work on the new version.

Things have been really slow on this project unfortunately.
